"""Background matting plugin backed by MatAnyone 2 (CVPR 2026).

Per-frame temporal-aware video matting via
``matanyone.InferenceCore.step()``. The first frame seeds the model's
memory with a binary mask (generated by ``rembg`` + BiRefNet-portrait);
subsequent frames reuse the temporal memory for stable edges and hair
quality.

Install with ``pip install eks-harness[matting]`` (pulls ``rembg``).
MatAnyone itself currently needs a one-off install from upstream
(``pip install --no-deps git+https://github.com/pq-yang/MatAnyone``
plus a matching ``torchvision`` build). Model weights auto-download on
first inference.
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING, Any, ClassVar

import numpy as np

from eks_harness.video.ir.effects import MatAnyoneRemove
from eks_harness.video.plugins.base import CompileTarget, Effect, FrameProcessor

if TYPE_CHECKING:
    from eks_harness.video.render.context import RenderContext

__all__ = ["MatAnyoneRemovePlugin"]

_LOG = logging.getLogger(__name__)


def _import_matanyone_or_raise() -> Any:
    try:
        from matanyone import InferenceCore  # type: ignore[import-not-found]
    except ImportError as exc:
        raise RuntimeError(
            "MatAnyoneRemove requires MatAnyone. Install with "
            "`pip install --no-deps git+https://github.com/pq-yang/MatAnyone` "
            "and ensure `torchvision` matches your `torch` build."
        ) from exc
    return InferenceCore


def _import_rembg_or_raise() -> Any:
    try:
        import rembg  # type: ignore[import-not-found]
    except ImportError as exc:
        raise RuntimeError(
            "MatAnyoneRemove first-frame mask requires `rembg`. "
            "Install with `pip install eks-harness[matting]`."
        ) from exc
    return rembg


class _MatAnyoneProcessor(FrameProcessor):
    """Frame-pipeline processor wrapping MatAnyone's temporal step() API."""

    parallel_safe: ClassVar[bool] = False

    def __init__(self, background: tuple[int, int, int, int]) -> None:
        self._background = background
        self._core: Any = None
        self._torch: Any = None
        self._rembg: Any = None
        self._mask_session: Any = None
        self._seeded: bool = False

    def process(self, frame: Any, t: float, frame_idx: int) -> Any:
        if self._core is None:
            return frame

        torch = self._torch
        h, w = frame.shape[:2]
        rgb = np.ascontiguousarray(frame[..., [2, 1, 0]])  # BGR -> RGB, uint8
        # MatAnyone expects float CHW in [0,1].
        image_t = (
            torch.from_numpy(rgb).permute(2, 0, 1).contiguous().float().div_(255.0)
        )
        device = next(self._core.network.parameters()).device
        image_t = image_t.to(device)

        if not self._seeded:
            # Generate the first-frame binary mask via rembg + BiRefNet-portrait.
            mask_rgba = self._rembg.remove(rgb, session=self._mask_session)
            alpha_u8 = mask_rgba[..., 3]
            seed_mask = (alpha_u8 > 127).astype(np.float32)
            mask_t = torch.from_numpy(seed_mask).float().to(device)
            prob = self._core.step(image_t, mask=mask_t, objects=[1], idx_mask=False)
            self._seeded = True
        else:
            prob = self._core.step(image_t)

        # prob shape: (num_objects, H, W) or (H, W). Reduce to single alpha.
        alpha = prob.detach().cpu().numpy()
        if alpha.ndim == 3:
            alpha = alpha[0] if alpha.shape[0] >= 1 else alpha.squeeze()
        alpha = np.clip(alpha, 0.0, 1.0)

        return _composite_bgr(alpha, frame, self._background)


class MatAnyoneRemovePlugin(Effect):
    name: ClassVar[str] = "matanyone_remove"
    model: ClassVar[type] = MatAnyoneRemove
    compile_targets: ClassVar[frozenset[CompileTarget]] = frozenset({"frame_pipeline"})

    def open(self, ir: MatAnyoneRemove, ctx: RenderContext) -> FrameProcessor:  # type: ignore[override]
        InferenceCore = _import_matanyone_or_raise()
        rembg = _import_rembg_or_raise()
        import torch  # MatAnyone hard-requires torch; checked transitively above.

        _LOG.info(
            "MatAnyoneRemove loading model weights (first run downloads ~400MB)"
        )
        # Identifier auto-downloads via HuggingFace.
        core = InferenceCore("PeiqingYang/MatAnyone")
        proc = _MatAnyoneProcessor(ir.background)
        proc._core = core
        proc._torch = torch
        proc._rembg = rembg
        from eks_harness.video.render.winml_ep import install_autoep_session_hook

        # Route rembg's ONNX session onto the AMD GPU (MIGraphX) when available;
        # it builds its own InferenceSession internally, so the hook is how we
        # reach it. No-op + CPU fallback when no GPU EP is present.
        install_autoep_session_hook()
        proc._mask_session = rembg.new_session("birefnet-portrait")
        return proc


def _composite_bgr(
    alpha: np.ndarray,
    src_bgr: np.ndarray,
    background: tuple[int, int, int, int],
) -> np.ndarray:
    """Alpha-blend the source BGR frame over ``background`` (RGBA tuple)."""

    h, w = src_bgr.shape[:2]
    if alpha.shape != (h, w):
        from PIL import Image

        a = Image.fromarray((alpha * 255).clip(0, 255).astype(np.uint8))
        a = a.resize((w, h), Image.BILINEAR)
        alpha = np.asarray(a, dtype=np.float32) / 255.0
    a3 = alpha[..., None].astype(np.float32)
    fg_bgr = src_bgr.astype(np.float32)
    # IR background is RGBA; convert to BGR for blending in BGR space.
    bg_bgr = np.array([background[2], background[1], background[0]], dtype=np.float32)
    out = fg_bgr * a3 + bg_bgr * (1.0 - a3)
    return np.clip(out, 0, 255).astype(np.uint8)
